##it will be set build date by gradle. if this value is @build.date@, front-end is development mode
#build.date=@build.date@
#server.port=8080
#server.address=localhost
#server.servlet.contextPath=/
#  # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
#server.servlet.encoding.charset=UTF-8
#  # Enable http encoding support.
#server.servlet.encoding.enabled=true
#  # Force the encoding to the configured charset on HTTP requests and responses.
#server.servlet.encoding.force=true
#
#spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#spring.data.web.pageable.one-indexed-parameters=true
#spring.datasource.url=jdbc:mysql://localhost:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.hikari.username=root
#spring.datasource.hikari.password=1234


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari :
      username : root
      password : 1234
  jpa :
    hibernate: